### ISSUE TITLE
NodeJS version support?

### ISSUE THREAD

**Issue by josephg** [kriszyp/weak-lru-cache#1]
This package seems to not work on some nodejs versions:

```
$ node
Welcome to Node.js v14.4.0.
Type ".help" for more information.
> const { WeakLRUCache } = require('weak-lru-cache');
Uncaught ReferenceError: WeakRef is not defined
    at new LRFUExpirer (/Users/josephg/src/sephstack/node_modules/weak-lru-cache/LRFUExpirer.js:13:25)
    at Object.<anonymous> (/Users/josephg/src/sephstack/node_modules/weak-lru-cache/index.js:113:24)
```

It'd be good to either fix the issue or mark supported nodejs versions in package.json and document the limitation in the readme.

**Comment by kriszyp** [comment]
Updated docs for this. I assume you are actually just trying get lmdb-store running though, and I fixed this so it shouldn't actually try instantiate unless it is used (which you probably aren't doing, since it isn't even documented yet).

**Comment by josephg** [comment]
Awesome! Yep sure am, though I ended up just updating nodejs and now it works fine locally. Still good to have it sorted to make deploys easier!
